In [3]:
import torch

In [4]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.randn((2, 3, 4))

tensor([[[-0.3774, -0.9163,  1.1601, -0.8285],
         [ 0.8597,  1.4358, -0.4245,  0.4761],
         [-0.8411, -0.5013,  1.0229, -0.6671]],

        [[ 0.3425, -1.2048,  0.6014, -0.3212],
         [-0.6545,  0.6136, -0.3285, -0.3014],
         [ 0.2598,  0.5236,  0.8609, -0.9545]]])

In [11]:
# basic usage for torch.tensor (xxx)