In [10]:
# Reading the dataset
## create a synthetic dataset and save it as house_tiny.csv
import os

os.makedirs(os.path.join(".", 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write("NumRooms,Alley,Price\n")
    f.write("NA,Pave,127500\n")
    f.write("2,NA,106000\n")
    f.write("4,NA,178100\n")
    f.write("NA,NA,140000\n")


In [12]:
# loading the dataset
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [14]:
# Handing missing data
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
inputs

D:\software\conda\envs\pytorch3d\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  This is separate from the ipykernel package so we can avoid doing imports until


NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [53]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs.values

array([[3., 1., 0.],
       [2., 0., 1.],
       [4., 0., 1.],
       [3., 0., 1.]])

In [17]:
# Conversion to the Tensor Format
import torch

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [4]:
# Summary

In [20]:
# Exercise (create a dataset with more columns and rows)
## delete the column with the most missing values
## convert the preprocessed dataset to the tensor format
new_data_file = os.path.join(".", "data", "student_exercise.csv")
with open(new_data_file, "w") as f:
    f.write("NameStud,Age,Grade,Graduate\n")
    f.write("Jason,25,NA,1\n")
    f.write("Linda,38,7,0\n")
    f.write("Jackson,13,1,0\n")
    f.write("Marry,17,3,1\n")
    f.write("Tony,34,NA,1\n")

In [61]:
stud_data = pd.read_csv(new_data_file)
stud_data

NameStud  Age  Grade  Graduate
0    Jason   25    NaN         1
1    Linda   38    7.0         0
2  Jackson   13    1.0         0
3    Marry   17    3.0         1
4     Tony   34    NaN         1

In [62]:
# delete the column
column_nona = stud_data.count().to_dict()
mini_column = min(column_nona, key=column_nona.get)
stud_data = stud_data.drop(columns=mini_column)
stud_data = pd.get_dummies(stud_data, dummy_na=True)
# stud_data.astype('int').values
stud_data

Age  Graduate  NameStud_Jackson  NameStud_Jason  NameStud_Linda  \
0   25         1                 0               1               0   
1   38         0                 0               0               1   
2   13         0                 1               0               0   
3   17         1                 0               0               0   
4   34         1                 0               0               0   

   NameStud_Marry  NameStud_Tony  NameStud_nan  
0               0              0             0  
1               0              0             0  
2               0              0             0  
3               1              0             0  
4               0              1             0

In [60]:
stud_tensor = torch.tensor(stud_data.values)
stud_tensor

tensor([[25,  1,  0,  1,  0,  0,  0,  0],
        [38,  0,  0,  0,  1,  0,  0,  0],
        [13,  0,  1,  0,  0,  0,  0,  0],
        [17,  1,  0,  0,  0,  1,  0,  0],
        [34,  1,  0,  0,  0,  0,  1,  0]])