In [9]:
# 1. Scalars
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [12]:
# 2. Vectors
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [14]:
## length, dimensionality, and shape
len(x), x.shape

(4, torch.Size([4]))

In [16]:
# 3. Matrices
A = torch.arange(20).reshape(5, 4)
A, A.T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

In [17]:
# 4. Tensors
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
# 5. Basic Properties of Tensor Airthmetric
# X = 

In [ ]:
# 6. Reduction
## Non-Reduction Sum

In [ ]:
# 7. Dot Products

In [ ]:
# 8. Matrix-Vector Products

In [ ]:
# 9. Matrix-Matrix Multiplication

In [2]:
# 10. Norms
## Norms and Objectives

In [3]:
# 11. More on Linear Algebra

In [4]:
# 12. Summary

In [5]:
# 13. Exercise